import { REQUEST_STATUSES } from '../utils/requestStatus';

export const sessionStatusOptions = [
  REQUEST_STATUSES.ACCEPTED,
  REQUEST_STATUSES.WAITING_STUDENT,
  REQUEST_STATUSES.IN_PROGRESS,
  REQUEST_STATUSES.COMPLETED,
  REQUEST_STATUSES.CANCELED,
];
