import { SESSION_STATUS } from './lifecycle';

export const sessionStatusOptions = [
  SESSION_STATUS.WAITING_STUDENT,
  SESSION_STATUS.IN_PROGRESS,
  SESSION_STATUS.COMPLETED,
  SESSION_STATUS.CANCELED,
  SESSION_STATUS.CANCELED_DURING,
];
